apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-tester
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vault-tester
  template:
    metadata:
      labels:
        app: vault-tester
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
